### ISSUE TITLE
change MultiGraph storage to adjacent list

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Multigraphs.jl#4]
https://github.com/QuantumBFS/Multigraphs.jl/blob/6e0c01a31f72141006860e0703fa335819eed6c4/src/multigraph.jl#L14

we need to make sure we have identical vertex ids in ZX, so we could have

```julia
struct Multigraph{T} <: AbstractMultigraph
     storage::Dict{T, Vector{T}}
end
```

**Comment by timmyfaraday** [comment]
Hi,

Since this change it has become impossible to initiate an empty Multigraph, i.e., Multigraph(0), because of `maximum(keys(adjlist))` when determining `_idmax` throwing an reduction over empty collection error.  

should be fixed by replacing the latter by `isempty(keys(adjlist)) ? 0 : maximum(keys(adjlist)) ` but this might not be the cleanest approach. 

Kind regard, Tom
